### ISSUE TITLE
Build problems (Linux)

### ISSUE THREAD

**Issue by a-mroz** [desura/Desurium#48]
Hi, 
I saw that  'install-deps.sh' has no Arch Linux option, so I tried to wrote mine. After that I wanted to test it, so tried to build Desurium. Third party built without problems, but I got an error while running build_lin/build.sh:

```
Traceback (most recent call last):
  File "../src/third_party/gyp/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/__init__.py", line 471, in main
    options.circular_check)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/__init__.py", line 111, in Load
    depth, generator_input_info, check, circular_check)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 2371, in Load
    ValidateTargetType(target, target_dict)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 2084, in ValidateTargetType
    (target, target_type, '/'.join(VALID_TARGET_TYPES)))
Exception: Target ../src/third_party/libs.gyp:gtk#target has an invalid target type 'settings'.  Must be one of executable/loadable_module/static_library/shared_library/none.
```

I wanted to check if that's not dependencies fault, so I switched to Fedora (16), ran 'install-deps.sh'. After that I tried to build third party, and got problems with curl and wxWidgets. 
- Curl gave me missing stropts.h. 
  I ran: `yum provides */stropts.h` and got `arm-gp2x-linux-glibc-2.3.6-9.fc15.noarch`. Arm - strange... But installing it fixed problem.
- wxWidgets gave me:
  `make: *** No rule to make target `/usr/lib/glib-2.0/include/glibconfig.h', needed by `monodll_utilscmn.o'.  Stop.`  And I'm not sure how I can fix it. 

I don't know if that's a bug, or I am doing something wrong, but help would be appreciated :)

Also I saw that link branding-> branding_default is made, so line "Copy branding_default in src to src/branding" in readme is probably no longer needed. Also lines for installing dependencies could be changed to just running install-deps.sh.

**Comment by Jookia** [comment]
Does this happen without install-deps.sh (stupid question, but have to make sure you didn't cause the problem yourself)

**Comment by matthiaskrgr** [comment]
Hi, I'm another archlinux user, and I got the same issue here.

I wonder if someone could make an  arch aur   building script which builds desurium.

**Comment by lodle** [comment]
the second error on fedora looks like a missing libgconfig. Try changing the target for gtk in libs.gyp from settings to none and see if that fixes your first issue.

**Comment by boskee** [comment]
Desurium also fails to build on Ubuntu 11.10. I will push my fix and send pull request shortly.

**Comment by a-mroz** [comment]
Ok, I made some progress :) 
- Arch:
  I removed Desurium sources and cloned it again (probably working on the same copy from two different systems wasn't the best idea...), changed 'settings' to 'none' in libs.gyp and it worked :) Didn't build cef yet, but I hope that it will be ok.
- Fedora:
  I somehow managed to build wxWidgets, but later there are some problems with libnotify:

```
Package libnotify was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnotify.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnotify' found
Traceback (most recent call last):
  File "../src/third_party/gyp/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/__init__.py", line
471, in main
    options.circular_check)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/__init__.py", line
111, in Load
    depth, generator_input_info, check, circular_check)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 2289,
in Load
    depth, check)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 387,
in LoadTargetBuildFile
    build_file_path)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 1003,
in ProcessVariablesAndConditionsInDict
    build_file, key)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 1010,
in ProcessVariablesAndConditionsInDict
    build_file)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 1029,
in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, is_late, variables, build_file)
  File "/home/sadam/Desurium/src/third_party/gyp/pylib/gyp/input.py", line 696,
in ExpandVariables
    (contents, p.returncode))
Exception: Call to 'pkg-config --libs-only-l libnotify' returned exit status 1.
while trying to load build.gyp
```

Later I will try again from scratch and see if that helps.

**Comment by datacompboy** [comment]
This error:
    Exception: Target ../src/third_party/libs.gyp:gtk#target has an invalid target type 'settings'.  Must be one of executable/loadable_module/static_library/shared_library/none.

fixed by change in ../src/third_party/libs.gyp type: settings to correct shared_library / static_library

**Comment by boskee** [comment]
@sadam36 Just install libnotify-devel rpm. That should be added to install-deps.sh, along with libnotify-dev for Debian/Ubuntu.

**Comment by a-mroz** [comment]
@boskee I saw libnotify installed, but didn't think about libnotify-devel, thanks. 

Now I am having problems with building cef - `third_party/build_lin/cef.log` ends with:

```
In file included from third_party/icu/public/common/unicode/strenum.h:14:0,
                 from third_party/icu/public/common/unicode/uenum.h:24,
                 from third_party/icu/public/common/unicode/uloc.h:25,
                 from third_party/icu/public/common/unicode/ubrk.h:12,
                 from base/i18n/break_iterator.cc:8:
third_party/icu/public/common/unicode/unistr.h: In member function ‘icu_46::UnicodeString& icu_46::UnicodeString::replace(int32_t, int32_t, UChar32)’:
third_party/icu/public/common/unicode/unistr.h:4024:9: error: variable ‘isError’ set but not used [-Werror=unused-but-set-variable]
third_party/icu/public/common/unicode/unistr.h: In member function ‘icu_46::UnicodeString& icu_46::UnicodeString::append(UChar32)’:
third_party/icu/public/common/unicode/unistr.h:4327:9: error: variable ‘isError’ set but not used [-Werror=unused-but-set-variable]
cc1plus: all warnings being treated as errors

make: *** [out/Release/obj.target/base_i18n/base/i18n/break_iterator.o] Error 1
```

I found  [here](http://groups.google.com/a/chromium.org/group/chromium-dev/browse_thread/thread/e5e9fadc974f7bfb) that it might be connected with having gcc 4.6 instead of 4.4, so installed gcc 4.4 from AUR, changed `/third_party/chromium/src/Makefile` but it didn't work (probably I should change other file...). I will try later build on fedora, and copying libcef_desura.so from desura.

**Comment by Jookia** [comment]
I gave up a while back on building cef.

**Comment by LarryRotgut** [comment]
After running /BuildCef.sh and it failed I did this to get it to compile:

$ cd ../chromium/src
$ rm -r out
$ cd cef
$ /usr/bin/python tools/gyp_cef cef.gyp -I cef.gypi -Dwerror=
$ cd ..
$ make cef_desura BUILDTYPE=Debug -j4
$ mv out/Debug/lib.target/libcef_desura.so ../../../../build_out/debug_lin/lib/
$ mv out/Debug/lib.target/libffmpegsumo.so ../../../../build_out/debug_lin/lib/

By default cef fails to build if there are any warnings since warnings are treated as errors. You have to specify "-Dwerror=" to get around it.

**Comment by Jookia** [comment]
Hmm. Could you put that in a pull request?

**Comment by higuita** [comment]
i'm on a slackware64 and manage to build desurium  just after the release, but not anymore...
with the latest tip
After changing the in the libs.gyp all `type: settings` to `type: shared_library` i gave it another try and now its giving errors the build in the wx_controls and uicore:

``````
-----------------------------------------------------------
 Building project wx_controls
-----------------------------------------------------------
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcButton.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcCheckBox.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcChoice.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcCombo.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcCustomFrameImpl.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcDialog.o
In file included from src/static/wx_controls/code/gcCustomFrameImpl.cpp:20:0:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcFrame.o
In file included from src/include/wx_controls/gcDialog.h:28:0,
                 from src/static/wx_controls/code/gcDialog.cpp:19:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcGrid.o
In file included from src/include/wx_controls/gcFrame.h:29:0,
                 from src/static/wx_controls/code/gcFrame.cpp:20:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcHyperlinkCtrl.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcImage.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcImageButton.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcImageControl.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcImgButtonCount.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcMessageBox.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcPanel.o
In file included from src/include/wx_controls/gcFrame.h:29:0,
                 from src/static/wx_controls/code/gcPanel.cpp:22:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
In file included from src/include/wx_controls/gcDialog.h:28:0,
                 from src/include/wx_controls/gcControls.h:29,
                 from src/include/wx_controls/gcMessageBox.h:25,
                 from src/static/wx_controls/code/gcMessageBox.cpp:20:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcProgressBar.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcRadioButton.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcScrolledWindow.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcStaticLine.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcStaticText.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcTaskBar.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcTextCtrl.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcToggleButton.o
In file included from src/include/wx_controls/gcFrame.h:29:0,
                 from src/static/wx_controls/code/gcTaskBar.cpp:23:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
src/static/wx_controls/code/gcTaskBar.cpp: In member function ‘bool gcTaskBarIcon::ShowBalloon(const wxString&, const wxString&, unsigned int, int)’:
src/static/wx_controls/code/gcTaskBar.cpp:308:8: error: too few arguments to function ‘NotifyNotification* notify_notification_new(const char*, const char*, const char*, GtkWidget*)’
/usr/include/libnotify/notification.h:79:21: note: declared here
make: *** [out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcTaskBar.o] Error 1
make: *** Waiting for unfinished jobs....

(...)

-----------------------------------------------------------
 Building project uicore
-----------------------------------------------------------
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcTaskBar.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcUpProgBar.o
  CXX(target) out/Debug/obj.target/wx_controls/src/static/wx_controls/code/guiDelegate.o
In file included from src/include/wx_controls/gcFrame.h:29:0,
                 from src/static/wx_controls/code/gcTaskBar.cpp:23:
src/include/wx_controls/gcCustomFrame.h: In constructor ‘gcCustomFrame<T>::gcCustomFrame(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
src/include/wx_controls/gcCustomFrame.h:48:62: warning: there are no arguments to ‘Create’ that depend on a template parameter, so a declaration of ‘Create’ must be available
src/include/wx_controls/gcCustomFrame.h:60:22: warning: there are no arguments to ‘GetSize’ that depend on a template parameter, so a declaration of ‘GetSize’ must be available
src/include/wx_controls/gcCustomFrame.h:60:38: warning: there are no arguments to ‘GetClientSize’ that depend on a template parameter, so a declaration of ‘GetClientSize’ must be available
src/include/wx_controls/gcCustomFrame.h:67:10: warning: there are no arguments to ‘Layout’ that depend on a template parameter, so a declaration of ‘Layout’ must be available
src/include/wx_controls/gcCustomFrame.h:68:15: warning: there are no arguments to ‘Refresh’ that depend on a template parameter, so a declaration of ‘Refresh’ must be available
src/static/wx_controls/code/gcTaskBar.cpp: In member function ‘bool gcTaskBarIcon::ShowBalloon(const wxString&, const wxString&, unsigned int, int)’:
src/static/wx_controls/code/gcTaskBar.cpp:308:8: error: too few arguments to function ‘NotifyNotification* notify_notification_new(const char*, const char*, const char*, GtkWidget*)’
/usr/include/libnotify/notification.h:79:21: note: declared here
make: *** [out/Debug/obj.target/wx_controls/src/static/wx_controls/code/gcTaskBar.o] Error 1
make: *** Waiting for unfinished jobs....```


any ideia?
``````

**Comment by Jookia** [comment]
Use the latest libnotify, or go to the line and screw with the ifdef.

**Comment by a-mroz** [comment]
@LarryRotgut thanks, It helped :)
I also built Desurium on Fedora - there was problem with `lstdc++` while building bootloader. I tried different packages and making symlinks, but no luck. What helped was removing `-static-libstdc++`  from `Desurium/src/executable/bootloader_lin/bootloader_lin.gyp` ;)

**Comment by aljones15** [comment]
in gentoo I had to replace all the type settings with none in order to the libs.gyp errors to go away. anyway compiling now hopefully it'll work.

**Comment by Jookia** [comment]
A reminder to you guys -- If you fix stuff, please submit a pull request.

**Comment by Jookia** [comment]
I fixed the settings -> none error on my fork. Will push soon.
